#!/bin/bash
export PATH="/usr/local/sbin:$PATH"

# TODO: read doc and move these to exports.local
export DOT_FILES="$HOME/dotfiles"
export PROJECTS="$HOME/projects"
export SCRIPTS="$PROJECTS/scripts"
