#!/bin/sh

#  A package manager for shell scripts.
if [ -d "$HOME/.basher" ] 
then
	local __shell="zsh"
	export PATH="$HOME/.basher/bin:$PATH"
	eval "$(basher init - ${__shell})" # replace `bash` with `zsh` if you use zsh
fi
