#!/bin/bash

# dotfiles
export PATH="$DOTPATH/bin:$PATH"

# neovim (probably)
export PATH="$PATH:/opt/nvim"

# homebrew
export PATH="/usr/local/sbin:$PATH"

export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"

export PATH="$HOME/.local/bin:$PATH"
export PATH="$PATH:/Users/q/projects/bro"

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# move to some osx dir
HOMEBREW_NO_AUTO_UPDATE=1

# TODO: read doc and move these to exports.local
