#!/bin/bash


 export NVM_DIR="$HOME/.nvm"

 nvm_default_version=$NVM_DIR/alias/default

 if [ -f "$nvm_default_version" ]; then
	 export PATH="$NVM_DIR/versions/node/$(<$nvm_default_version)/bin:$PATH"
 fi

 function source_nvm() {
	 [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
	   [ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
 }

 # https://github.com/nvm-sh/nvm/issues/1277
 alias nvm="unalias nvm; source_nvm; nvm $@"
