#!/bin/bash

# find
function f() {
	find . -type f -print0 | xargs -0 grep -i $1;
}

# find file
function ff() {
	list=$(find . -name "*$1*");
	n=$(echo "$list" | wc -l);
	printf "$n results found: \n$list\n"
	cat $list
}

function source_profile() {
	source ~/.bash_profile
}

function edit_dotfiles() {
	subl $DOT_FILES
}

function log {
   echo $(date +"%b %d %T") $1
}

function rm_broken_symlink() {
	find -L . -name . -o -type d -prune -o -type l -exec rm {} +
}
