#!/bin/bash

# dotfiles
export PATH="$DOTPATH/bin:$PATH"

# homebrew
export PATH="/usr/local/sbin:$PATH"


export PATH="$HOME/.rbenv/bin:$PATH"
export PATH="$PATH:$HOME/.composer/vendor/bin"
export PATH="$PATH:$HOME/Library/Android/sdk/platform-tools"


export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

# TODO: read doc and move these to exports.local
