#!/bin/bash

RBENV_DIR="$HOME/.rbenv"

if [ ! -d $RBENV_DIR ]; then
	return;
fi

# export PATH="$RBENV_DIR/shims:${PATH}"
# export RBENV_SHELL=zsh

# . $RBENV_DIR/libexec/../completions/rbenv.zsh

# command rbenv rehash 2>/dev/null

# rbenv() {
#   local command
#   command="$1"
#   if [ "$#" -gt 0 ]; then
#     shift
#   fi

#   case "$command" in
#   rehash|shell)
#     eval "$(rbenv "sh-$command" "$@")";;
#   *)
#     command rbenv "$command" "$@";;
#   esac
# }

eval "$(rbenv init -)"