#!/bin/bash


export NVM_DIR="$HOME/.nvm"

nvm_default_version=$NVM_DIR/alias/default

if [ -f "$nvm_default_version" ]; then
	export PATH="$NVM_DIR/versions/node/$(<$nvm_default_version)/bin:$PATH"
fi

function source_nvm() {
	[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
	[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

# https://github.com/nvm-sh/nvm/issues/1277
alias nvm="unalias nvm; source_nvm; nvm $@"