#!/bin/bash
export PATH="/usr/local/sbin:$PATH"
export PATH="$HOME/.rbenv/bin:$PATH"
# TODO: read doc and move these to exports.local
export DOT_PATH="$HOME/dotfiles"
export PROJECTS="$HOME/projects"
export SCRIPTS="$PROJECTS/scripts"
