source ~/.profile
#!/bin/sh 

#[ -f ~/.bashrc ] && . ~/.bashrc 


export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

complete -C /opt/homebrew/bin/terraform terraform
