#!/bin/sh -e

[ -f ~/.source_vital ] && . ~/.source_vital

# sourcing my own functions and exports etc.
[ -f "$DOTPATH/etc/lib/login_source.sh" ] && . "$DOTPATH/etc/lib/login_source.sh"

# bash specific stuff goes here
if [ -f `brew --prefix`/etc/bash_completion.d/rails]; then
    source `brew --prefix`/etc/bash_completion.d/rails
fi

#export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
#export PATH=$PATH:$JAVA_HOME
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/platform-tools

[[ -f ~/.bash-preexec.sh ]] && source ~/.bash-preexec.sh
eval "$(atuin init bash)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
