#!/bin/sh -e

[ -f ~/.source_vital ] && . ~/.source_vital

# sourcing my own functions and exports etc.
[ -f "$DOTPATH/etc/lib/login_source.sh" ] && . "$DOTPATH/etc/lib/login_source.sh"

# bash specific stuff goes here
if [ -f `brew --prefix`/etc/bash_completion.d/rails]; then
    source `brew --prefix`/etc/bash_completion.d/rails
fi
