
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

"set runtimepath+=~/dotfiles
call plug#begin()

"Plug 'ervandew/supertab' " tab auto completion
Plug 'tpope/vim-sensible'
" Plug 'bash-support.vim'
"Plug 'kien/ctrlp.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'powerline/powerline', {'rtp': 'powerline/bindings/vim/'}
Plug 'scrooloose/nerdcommenter'
Plug 'stanangeloff/php.vim'
Plug 'tpope/vim-markdown'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'joonty/vim-phpqa'
" Plug 'shawncplus/phpcomplete.vim'
Plug 'tpope/vim-surround' " braces etc.
Plug 'schickling/vim-bufonly' " braces etc.
Plug 'tmhedberg/SimpylFold'
" Plug 'vim-scriptsindentpython.vim' " python indent
" Plug 'Valloric/YouCompleteMe' " python autocomplete
"Plug 'ycm-core/YouCompleteMe'
Plug 'scrooloose/syntastic' " python lint
"Plug 'nvie/vim-flake8' "Flake8, a static syntax and style checker for
Plug 'dkprice/vim-easygrep'
Plug 'tpope/vim-fugitive'
" Plug 'tomlion/vim-solidity'
Plug 'vim-ruby/vim-ruby'
Plug 'ecomba/vim-ruby-refactoring'
Plug 'tpope/vim-rails'
Plug 'tpope/vim-rbenv'
Plug 'tpope/vim-bundler'
Plug 'honza/vim-snippets'
Plug 'MarcWeber/vim-addon-mw-utils'
Plug 'tomtom/tlib_vim'
"Plug 'garbas/vimsnipmate'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-endwise'
Plug 'dense-analysis/ale'
Plug 'ludovicchabant/vim-gutentags'
Plug 'unkiwii/vim-nerdtree-sync'
Plug 'tpope/vim-abolish' "search and replace with case
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'arcticicestudio/nord-vim'
Plug 'morhetz/gruvbox'
Plug 'ngmy/vim-rubocop'
Plug 'bkad/CamelCaseMotion'
Plug 'pangloss/vim-javascript'    " JavaScript support
Plug 'leafgarland/typescript-vim' " TypeScript syntax
Plug 'maxmellon/vim-jsx-pretty'   " JS and JSX syntax
Plug 'jparise/vim-graphql'        " GraphQL syntax
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'airblade/vim-rooter'
Plug 'ryanoasis/vim-devicons'
call plug#end()

"source ~/.vim/custom/*.vim

" Leader key is SPACE, I find it the best
let mapleader = " "
set lazyredraw " Don’t update screen during macro and script execution.
set updatetime=300 "time before swap file is written to disk"
" Faster saving and exiting
nnoremap <silent><leader>w :w!<CR>
nnoremap <silent><leader>q :q!<CR>
nnoremap <silent><leader>x :x<CR>
" Open Vim configuration file for editing
nnoremap <silent><leader>2 :e ~/.vimrc<CR>
" Source Vim configuration file and install plugins
nnoremap <silent><leader>1 :source ~/.vimrc \| :PlugInstall<CR>


" Nerdtree configuration
let g:deoplete#enable_at_startup = 1
let g:NERDTreeHighlightCursorline = 1
let g:nerdtree_sync_cursorline = 1

set runtimepath+=~/dotfiles
runtime! etc/init/vim/**.vim
" Allow copy and paste from system clipboard
set clipboard=unnamed

set ignorecase " Ignore case when searching
set smartcase  " When searching try to be smart about cases
set nohlsearch " Don't highlight search term
set incsearch  " Jumping search

set encoding=utf-8

" let netrw be a tree
let g:netrw_liststyle=3

" remove warning for snipMate
"let g:snipMate = { 'snippet_version' : 1 }

" configure linters here
let g:ale_linters = {
      \   'ruby': ['standardrb', 'rubocop'],
      \   'python': ['flake8', 'pylint'],
      \   'javascript': ['eslint'],
      \}
let g:ale_fix_on_save = 1
" display linter warnings in status bar
function! LinterStatus() abort
  let l:counts = ale#statusline#Count(bufnr(''))

  let l:all_errors = l:counts.error + l:counts.style_error
  let l:all_non_errors = l:counts.total - l:all_errors

  return l:counts.total == 0 ? '✨ all good ✨' : printf(
        \   '😞 %dW %dE',
        \   all_non_errors,
        \   all_errors
        \)
endfunction

set statusline=
set statusline+=%m
set statusline+=\ %f
set statusline+=%=
set statusline+=\ %{LinterStatus()}



syntax enable
set background=dark
 let g:solarized_termcolors=256
let g:solarized_termtrans =   1
let g:solarized_degrade   =   0
let g:solarized_bold      =   1
let g:solarized_underline =   1
let g:solarized_italic    =   1
let g:solarized_contrast  =   "high" | "normal"|   "high" or "low"
let g:solarized_visibility=   "high" | "normal"|   "high" or "low"
silent! colorscheme solarized
if has("gui_running")
  syntax on
  set hlsearch
  colorscheme nord
  set bs=2 " backspace
  set ai " auto indent
  set ruler " lines colonne
  set guifont=Hack\ Nerd\ Font:h14
endif

autocmd! GUIEnter * set vb t_vb=
"autocmd vimenter * ++nested colorscheme gruvbox
" activate mouse
set mouse=a


filetype plugin on

" ::::::::: Initialization ::::::::::::::::
syntax enable



" display line numbers
set number
" set foldcolumn=3
" set nuw=6

" start NerdTree when vim starts
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd VimEnter * NERDTree | wincmd p
let NERDTreeShowHidden=1
let NERDTreeIgnore = ['\.pyc$', '\.swp']

" inserts new lines
"
map <Enter> o<ESC>
map <S-Enter> O<ESC>

" Tab navigation (broken)
"map  <C-l> :tabn<CR>
"map  <C-h> :tabp<CR>
"map  <C-n> :tabnew<CR>
"map  <C-Right> :tabn<CR>
"map  <C-Left> :tabp<CR>

" SuperTab recommended settings (no explanation...)
let g:SuperTabDefaultCompletionType = ""

set tabstop=4 softtabstop=0 noexpandtab shiftwidth=4 

" [TEST]: spaces in nno => insert mode
"nnoremap <space> i<space>
"nnoremap <tab> i<tab>
"nnoremap <BS> i<BS>

set incsearch "incremental search
set hlsearch "highlight search


" Change cursor shape between insert and normal mode in iTerm2.app
if $TERM_PROGRAM =~ "iTerm.app"
    let &t_SI = "\<Esc>]50;CursorShape=1\x7" " Vertical bar in insert mode
    let &t_EI = "\<Esc>]50;CursorShape=0\x7" " Block in normal mode
endif

" guten-tags & ctags management
 let g:gutentags_ctags_tagfile= ".tags"
"

" rm search highligth
" nnoremap <esc> :noh<return><esc>

" hard mode
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

"set foldmethod=indent
noremap 4 :BufOnly<CR>

"nerdtree reveal in tree
nmap <leader>r :NERDTreeFind<CR>
"toggle nerdtree
nmap ,m :NERDTreeToggle<CR>
" open nerd tree
map <C-n> :NERDTreeToggle<CR>


let &titlestring = $USER . "@" . hostname() . " " . expand("%:p")
if &term == "screen"
  set t_ts=^[k
  set t_fs=^[\
endif
if &term == "screen" || &term == "xterm"
  set title
endif


" <<< quit vim if last buffer
autocmd WinEnter * call s:CloseIfOnlyNerdTreeLeft()

" Close all open buffers on entering a window if the only
" buffer that's left is the NERDTree buffer
function! s:CloseIfOnlyNerdTreeLeft()
  if exists("t:NERDTreeBufName")
    if bufwinnr(t:NERDTreeBufName) != -1
      if winnr("$") == 1
        q
      endif
    endif
  endif
endfunction


" >>> quit vim if last buffer


"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
"
"


" Enable folding
set foldmethod=indent
set foldlevel=99
" Enable folding with the spacebar
" nnoremap <space> za


" PEP8 standarts (python)
au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix |

" other standarts
au BufNewFile,BufRead *.js,*.html,*.css
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2 |


" Flagging Unnecessary Whitespace
highlight BadWhitespace ctermbg=red guibg=darkred
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/


" python Auto-complete
"let g:ycm_autoclose_preview_window_after_completion=1
"map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>


""python with virtualenv support
""TODO :disabled because it fails on install
"py << EOF
"import os
"import sys
"if 'VIRTUAL_ENV' in os.environ:
"  project_base_dir = os.environ['VIRTUAL_ENV']
"  activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
"  execfile(activate_this, dict(__file__=activate_this))
"EOF

" nice python
let python_highlight_all=1
syntax on


let g:EasyGrepRecursive=1
let g:EasyGrepIgnoreCase=1 
let g:EasyGrepHidden=1


if executable('ag')
  let g:ctrlp_user_command = 'ag %s -l --nocolor --hidden -g ""'
endif

" https://github.com/kien/ctrlp.vim/issues/646
let g:ctrlp_prompt_mappings = {
    \ 'AcceptSelection("e")': ['<2-LeftMouse>'],
    \ 'AcceptSelection("t")': ['<cr>'],
    \ }

let g:nerdtree_tabs_open_on_console_startup=1
let g:ctrlp_show_hidden = 1
" Navigating tabs
nmap <leader>[ :tabprevious<CR>
nmap <leader>] :tabnext<CR>

" Alt-right/left to navigate forward/backward in the tags stack
map <C-H> <C-T>
map <C-L> <C-]>


if has("gui_running")
	" MacVim Touch Bar support
	" ========================
	" Since version 8.0 (I think), MacVim natively supports the macOS touch bar. By default it just contains 
	" one button to toggle fullscreen mode. To add some more useful buttons, just copy this into your .vimrc
	"
	" More details about the syntax can be found here: https://github.com/macvim-dev/macvim/blob/master/runtime/doc/gui_mac.txt
	" For a list of touch bar image names, see https://developer.apple.com/design/human-interface-guidelines/macos/touch-bar/touch-bar-icons-and-images/


	" Toggle NerdTree
	an icon=NSTouchBarSidebarTemplate TouchBar.NerdTree :NERDTreeToggle<CR> 

	an TouchBar.-flexspace2- <Nop>

	" List buffers
	an icon=NSTouchBarListViewTemplate TouchBar.ListBuffers :ls<CR>
	" Delete buffer
	an icon=NSTouchBarDeleteTemplate TouchBar.Delete :bd<CR>

	an TouchBar.-Sep- <Nop> 

	" Previous buffer
	an icon=NSTouchBarGoBackTemplate TouchBar.GoBack :bp<CR>
	" Next buffer
	an icon=NSTouchBarGoForwardTemplate TouchBar.GoForward :bn<CR>
	anoremenu 1.1 TouchBar.-flexspace- <Nop>
	tlnoremenu 1.1 TouchBar.-flexspace- <Nop>

endif




" Rubocop integration
let g:vimrubocop_keymap = 0
"nmap <Leader>r :RuboCop<CR>
"duplicate a line without adding it to the register
map <Leader>j :co.<CR> 
let g:coc_global_extensions = [ 'coc-tsserver' ]

nnoremap <C-g> :Ag<Cr>
nnoremap <C-p> :GFiles<Cr>
" CoC extensions
let g:coc_global_extensions = ['coc-solargraph', 'coc-tsserver', 'coc-json']

" Add CoC Prettier if prettier is installed
if isdirectory('./node_modules') && isdirectory('./node_modules/prettier')
  let g:coc_global_extensions += ['coc-prettier']
endif

" Add CoC ESLint if ESLint is installed
if isdirectory('./node_modules') && isdirectory('./node_modules/eslint')
  let g:coc_global_extensions += ['coc-eslint']
endif

" Camelcase configuration
let g:camelcasemotion_key = '<leader>'
map <silent> w <Plug>CamelCaseMotion_w
map <silent> b <Plug>CamelCaseMotion_b
map <silent> e <Plug>CamelCaseMotion_e
map <silent> ge <Plug>CamelCaseMotion_ge
sunmap w
sunmap b
sunmap e
sunmap ge

" Coc configuration
" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup

" Give more space for displaying messages.
set cmdheight=2
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1

" Automatically save the session when leaving Vim
"autocmd! VimLeave * mksession
" Automatically load the session when entering vim
"autocmd! VimEnter * source ./Session.vim
"
set noswapfile

" start scrolling when near buffer hedges
set scrolloff=10

" avoid line break
set wrapmargin=0
set textwidth=0

