emulate sh
source ~/.profile
emulate zsh


[ -f ~/.source_vital ] && . ~/.source_vital


[ -f "$DOTPATH/etc/lib/profile_source.sh" ] && . "$DOTPATH/etc/lib/profile_source.sh"

# Created by `pipx` on 2024-09-03 07:06:45
export PATH="$PATH:/Users/q/.local/bin"
