cask_args appdir: '/Applications'

tap 'caskroom/versions'
brew tap josegonzalez/homebrew-php


brew 'ant'
brew 'git'
brew 'gradle'
brew 'mysql'
brew 'python'
brew 'python3'
#brew 'sbt'
#brew 'scala'
#brew 'tig'
#brew 'wget'

# wordpress client
brew 'wp-cli'


#cask 'atom'
#cask 'dashlane'
cask 'dropbox'
#cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
#cask 'slack'
#cask 'spectacle'
cask 'sublime-text3'
cask 'vlc'
cask 'sequel-pro'

tap 'thoughtbot/formulae'
brew 'rcm'